source "%val{config}/plugins/plug.kak/rc/plug.kak"

colorscheme desertex

set-option global tabstop 2
set-option global indentwidth 2
plug 'andreyorst/smarttab.kak' defer smarttab %{
  set-option global softtabstop 2
} config %{
  hook global WinSetOption .* expandtab
}

# eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(python|c|cpp) %{
  # lsp-enable-window
  # lsp-auto-hover-enable
}

add-highlighter global/ number-lines

# macro recording/playback on ^ instead of q
map global normal ^ q
map global normal <a-^> Q

# backwards word on q instead of b
map global normal q b
map global normal Q B
map global normal <a-q> <a-b>
map global normal <a-Q> <a-B>

# user mode (,)
map global user m ':make<ret>'

plug "Delapouite/kakoune-buffers" config %(
  map global normal b ':enter-buffers-mode<ret>'              -docstring 'buffers…'
  map global normal B ':enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'
)

plug "s-ol/zig.kak"

plug "eraserhd/parinfer-rust" do %{
  cargo install --force --path .
  cargo clean
} config %{
  hook global WinSetOption filetype=(clojure|lisp|scheme|racket) %{
    parinfer-enable-window -smart
  }
}

def ide %{
  rename-client main
  set global jumpclient main

  new rename-client tools_docs
  set global toolsclient tools_docs
  set global docsclient tools_docs
}

def presentation %{
  set global autoinfo ''
  set global autocomplete ''
  addhl global/ wrap -word -indent
}

plug 'alive.kak'

hook global ModuleLoaded x11 %{
  set-option global termcmd "urxvtc -e sh -c"
}
